language: python
python:
  - 3.6.8
services:
  - docker
before_install:
  - docker build --tag -f $DOCKER_USERNAME/datageneratorapp .
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker push $DOCKER_USERNAME/flaskhelloworld
