apiVersion: v1
kind: Service
metadata:
  name: datageneratordash-nodeport
spec:
  type: NodePort
  ports:
  - name: serviceflask
    port: 80
    targetPort: httpflask
  selector:
    app: datageneratordash
