apiVersion: v1
kind: Pod
metadata:
  name: datageneratordash
spec:
  containers:
  - image: barteks/datageneratorapp
    name: datagenerator
    args: ["--data_path=/var/datasink/data.json"]
    volumeMounts:
    - name: datasource
      mountPath: /var/datasink
  - image: barteks/datagenerateddashboard
    name: dashboard
    args: ["--data_path=/var/datasource/data.json"]
    volumeMounts:
    - name: datasource
      mountPath: /var/datasource
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: datasource
    emptyDir: {}
